name: Spider-Sense
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=eigen
  - absl-py=0.13.0=py38haa95532_0
  - aiohttp=3.8.1=py38h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=0.13.1=py38_0
  - astor=0.8.1=py38haa95532_0
  - astroid=2.6.6=py38haa95532_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - async_generator=1.10=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - av=8.0.3=py38hf05fafe_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py38he774522_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - blinker=1.4=py38haa95532_0
  - blosc=1.21.0=h19a0ad4_0
  - bottleneck=1.3.2=py38h2a96729_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.10.26=haa95532_2
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py38haa95532_0
  - cffi=1.15.0=py38h2bbff1b_0
  - cfitsio=3.470=he774522_6
  - chardet=4.0.0=py38haa95532_1003
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cookiecutter=1.7.2=pyhd3eb1b0_0
  - cryptography=3.4.8=py38h71e12ea_0
  - cudatoolkit=11.1.1=heb2d755_7
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py38he774522_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - docutils=0.17.1=py38haa95532_1
  - entrypoints=0.3=py38_0
  - ffmpeg=4.3.1=ha925a31_0
  - fire=0.4.0=pyh44b312d_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - frozenlist=1.2.0=py38h2bbff1b_0
  - fsspec=2021.10.1=pyhd3eb1b0_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h62dcd97_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - h5py=2.10.0=py38h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.3=pyhd3eb1b0_0
  - imagecodecs=2021.8.26=py38ha1f97ea_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py38haa95532_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - inflection=0.5.1=py38haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.4.1=py38haa95532_1
  - ipython=7.29.0=py38hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.0=py38haa95532_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_2
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - keras=2.4.3=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.4.3=pyhd3eb1b0_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keyring=23.4.0=py38haa95532_0
  - kiwisolver=1.3.1=py38hd77b12b_0
  - lazy-object-proxy=1.6.0=py38h2bbff1b_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libdeflate=1.8=h2bbff1b_5
  - libiconv=1.15=vc14h29686d3_5
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.17.2=h23ce68f_1
  - libspatialindex=1.9.3=h6c2663c_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - libxml2=2.9.12=h0ad7f3c_0
  - libxslt=1.1.34=he774522_0
  - libzopfli=1.0.3=ha925a31_0
  - locket=0.2.1=py38haa95532_1
  - lxml=4.6.1=py38h1350720_0
  - lz4-c=1.9.3=h2bbff1b_1
  - markdown=3.3.4=py38haa95532_0
  - markupsafe=1.1.1=py38he774522_0
  - matplotlib=3.3.4=py38haa95532_0
  - matplotlib-base=3.3.4=py38h49ac443_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38he774522_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - multidict=5.1.0=py38h2bbff1b_2
  - mypy_extensions=0.4.3=py38_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - ninja=1.10.2=py38h559b2a2_3
  - numexpr=2.7.3=py38hb80d3ca_1
  - numpy-base=1.21.2=py38h0829f74_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=1.1.1l=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.4=py38h6214cd6_0
  - pandocfilters=1.4.3=py38haa95532_1
  - paramiko=2.7.2=py_0
  - parso=0.8.2=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pathspec=0.7.0=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.0.0=py38hca74424_0
  - pip=21.2.2=py38haa95532_0
  - pluggy=1.0.0=py38haa95532_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.8.0=py38h2bbff1b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyjwt=2.1.0=py38haa95532_0
  - pylint=2.9.6=py38haa95532_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.4.0=py38h62dcd97_1
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyreadline=2.1=py38_1
  - pyrsistent=0.18.0=py38h196d8e1_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.10=hdbf39b2_7
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38he774522_2
  - pywin32=228=py38hbaba5e8_1
  - pywin32-ctypes=0.2.0=py38_1000
  - pyyaml=6.0=py38h2bbff1b_1
  - pyzmq=22.3.0=py38hd77b12b_2
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - regex=2021.8.3=py38h2bbff1b_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rope=0.21.1=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=0.9.7=py38h2eaa2aa_1
  - scikit-image=0.18.1=py38hf11a4ad_0
  - scipy=1.7.1=py38hbe87c03_2
  - setuptools=58.0.4=py38haa95532_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=h33f27b4_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sphinx=4.2.0=pyhd3eb1b0_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.1.5=py38haa95532_1
  - spyder-kernels=2.1.3=py38haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - tensorflow=2.3.0=mkl_py38h8c0d9a2_0
  - tensorflow-base=2.3.0=eigen_py38h75a453f_0
  - termcolor=1.1.0=py38haa95532_1
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.11=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.9.0=py38
  - torchvision=0.10.0=py38_cu111
  - tornado=6.1=py38h2bbff1b_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py38h2bbff1b_1
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - ujson=4.0.2=py38hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=2.1.6=py38haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - whichcraft=0.6.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - wrapt=1.12.1=py38he774522_1
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.6.3=py38h2bbff1b_0
  - youtube-dl=2021.6.6=py38haa244fe_0
  - zfp=0.5.5=hd77b12b_6
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - albumentations==1.0.3
    - attr==0.3.1
    - configparser==5.0.2
    - coremltools==4.1
    - distro==1.6.0
    - docker-pycreds==0.4.0
    - dominate==2.6.0
    - flatbuffers==2.0
    - gitdb==4.0.7
    - gitpython==3.1.18
    - glog==0.3.1
    - grpcio==1.38.1
    - joblib==1.0.1
    - json-tricks==3.15.5
    - jsonpatch==1.32
    - jsonpointer==2.1
    - mpmath==1.2.1
    - munch==2.5.0
    - numpy==1.21.1
    - onnx==1.10.0
    - onnx-simplifier==0.3.6
    - onnxoptimizer==0.2.6
    - onnxruntime==1.8.1
    - opencv-contrib-python==4.5.3.56
    - opencv-python==4.5.3.56
    - opencv-python-headless==4.5.3.56
    - openpose-pytorch==0.1.0
    - pafy==0.5.5
    - pathtools==0.1.2
    - pretrainedmodels==0.7.4
    - promise==2.3
    - protobuf==3.17.3
    - pyasn1-modules==0.2.8
    - pyblur==0.2.3
    - python-gflags==3.1.2
    - pytube==12.0.0
    - scikit-build==0.12.0
    - scikit-learn==0.19.2
    - seaborn==0.11.1
    - sentry-sdk==1.3.0
    - shortuuid==1.0.1
    - smmap==4.0.0
    - ssim==0.3.0
    - subprocess32==3.5.4
    - sympy==1.8
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - tensorflow-estimator==2.3.0
    - thop==0.0.31-2005241907
    - torchfile==0.1.0
    - torchsummary==1.5.1
    - visdom==0.1.8.9
    - wand==0.6.7
    - wandb==0.11.0
    - websocket-client==1.1.0
    - werkzeug==2.0.1
    - yacs==0.1.8
prefix: C:\Users\derph\Miniconda3\envs\Spider-Sense
